# Generated by Django 2.2.5 on 2019-11-10 22:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='%d/%m/%Y %H:%M:%S')),
                ('end_datetime', models.DateTimeField(verbose_name='%d/%m/%Y %H:%M:%S')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Mobile number must be a valid 12 digit UK number.', regex='^\\+44\\d{10}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='item_image')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webay.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bid_datetime', models.DateTimeField(verbose_name='%d/%m/%Y %H:%M:%S')),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='webay.Auction')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='webay.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='webay.Item'),
        ),
    ]
